version: '3.7'

services:
  
  db:
    image: mariadb
    ports:
      - "3308:3306"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d/      
    environment:
      MYSQL_DATABASE: Dnd
      MYSQL_USER: admin
      MYSQL_PASSWORD: Master
      MYSQL_ROOT_PASSWORD: pestillo

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
